version: "3.7"

services:
  app:
    container_name: d2a_app
    build:
      context: .
    environment:
      - LANG='en_US.UTF-8'
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
    command: /bin/bash
    working_dir: /root/
    volumes:
      - ./:/root/
    command: >
      /bin/bash -c "
        python -m venv venv/ || true &&
        venv/bin/pip install pip setuptools -U &&
        venv/bin/pip install wheel &&
        venv/bin/pip install -r demo_requirements.txt &&
        bash
      "
    privileged: true
    ports:
    - "1310:1310"
    

  postgres:
    container_name: d2a_postgres
    image: postgis/postgis:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: d2a
      POSTGRES_PASSWORD: d2a
      POSTGRES_DB: d2a
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/
    expose:
      - "5432"

  mysql:
    image: mariadb:latest
    container_name: d2a_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'd2a'
      MYSQL_USER: 'd2a'
      MYSQL_PASSWORD: 'd2a'
      # MYSQL_DATABASE: mysql
    volumes:
      - ./data/mysql/:/var/lib/
    expose:
      - "3306"

networks:
  d2a-network:
